name: Tests

on: [push,pull_request]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html

    - name: Run tests and generate report
      run: |
        pytest tests\test.py --html=report.html --self-contained-html

    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html

    - name: Upload source code as artifact
      uses: actions/upload-artifact@v4
      with:
        name: source-code
        path: .

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Deploy code
      run: |
        echo "Deploying code..."

  
